---
title: "Time-varying confounding?"
format: html
editor: visual
---

```{r, echo = F, message=F}
library(dplyr)
library(survival)

rfiles <- "../R/"
dataloc <- "../data/"

source(paste0(rfiles, "test_settings_update.R"))

```

### Settings (no treatment effect, no confounding)

```{r, echo = FALSE}
bind_rows(
  "Severity" = 0:1,
  "Probability of treatment" = trt_by_sev,
  "Outcome under no treatment" = out_by_sev_trt0, 
  "Outcome under treatment" = out_by_sev_trt1
  ) |> 
  tidyr::pivot_longer(cols = -Severity) |> 
  tidyr::pivot_wider(id_cols = name, names_from = Severity) |> 
  kableExtra::kable(col.names = c("", "Low severity", "High severity"))
```

### Example data structure

```{r, echo = F}
long_pop1 |> 
  dplyr::filter(trajid == 108) |> 
  dplyr::select(trajid, visit, sev, trt, t, delta) |> 
  kableExtra::kable(col.names = c("ID", "Visit", "Severity", "Treatment", "TTE", "Indicator"))
```

### Example data structure (converted to long with time-varying severity)

```{r, echo = F}
hold |> 
  dplyr::filter(trajid == 108) |> 
  dplyr::select(trajid, visit, index, sev0, sev, trt, t_in, t_out, delta, ipcw) |> 
  kableExtra::kable(col.names = c("ID", "Visit", "Index", "Baseline severity", "Severity", "Treatment", "Time in", "Time out", "Indicator", "IPCW"))
```

### Severity indices contributed by treatment and baseline severity

```{r, echo = F, message=FALSE}
hold |> 
  dplyr::filter(t_out <= 3) |> 
  dplyr::group_by(sev0, trt) |> 
  dplyr::summarize(
    `Proportion of high severity visits` = formatC(sum(sev*prob*ipcw)/sum(prob*ipcw), digits = 3)
  ) |> 
  kableExtra::kable(col.names = c("Baseline severity", "Treatment", "Proportion of high severity visits"))
```

### Risks overall and stratified by "baseline" risk

```{r, echo = F}
bind_rows(
  all |> dplyr::mutate(stratum = "overall"),
  sev0 |> dplyr::mutate(stratum = "severity = 0"),
  sev1 |> dplyr::mutate(stratum = "severity = 1")
) |> 
  dplyr::transmute(
    stratum,
    `Treated risk` = formatC(risk1, digits = 3),
    `Untreated risk` = formatC(risk0, digits = 3)
  ) |> 
  kableExtra::kable()
```
